version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ubuntu/myapp
  - source: scripts
    destination: /home/ubuntu/myapp/scripts
permissions:
  - object: /home/ubuntu/myapp
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu