name: Java CI with Maven and AWS Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Zip the build directory
        run: |
          zip -r app-${{ github.sha }}.zip target/*.jar appspec.yml scripts/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload ZIP to S3
        run: |
          aws s3 cp app-${{ github.sha }}.zip s3://springcicd/app-${{ github.sha }}.zip

      - name: Check ZIP contents
        run: unzip -l app-${{ github.sha }}.zip

      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name sss \
            --deployment-group-name sss \
            --s3-location bucket=springcicd,key=app-${{ github.sha }}.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE

